apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o deploy/dev_distributed/resources
    kompose.version: 1.28.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: connector
  name: connector
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: connector
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o deploy/dev_distributed/resources
        kompose.version: 1.28.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/clickhouse-kafka-connect-default: "true"
        io.kompose.service: connector
    spec:
      containers:
        - args:
            - bash
            - -c
            - |
              echo "Launching Kafka Connect worker"
              sleep 20
              /etc/confluent/docker/run &
              bash -c 'while [[ "$()(curl -s -o /dev/null -w ''%{http_code}'' localhost:8083)" != "200" ]]; do sleep 5; done'
              curl -s -X PUT -H  "Content-Type:application/json" http://localhost:8083/connectors/kafka-clickhouse/config \
                  -d '{
                  "connector.class": "com.clickhouse.kafka.connect.ClickHouseSinkConnector",
                  "tasks.max": 1,
                  "topics": "connect-test,github",
                  "hostname": "clickhouse",
                  "port": 8123,
                  "exactlyOnce": true
              }'
              sleep infinity
          env:
            - name: CONNECT_BOOTSTRAP_SERVERS
              value: broker:9092
            - name: CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR
              value: "1"
            - name: CONNECT_CONFIG_STORAGE_TOPIC
              value: _connect-configs
            - name: CONNECT_GROUP_ID
              value: kafka-connect
            - name: CONNECT_INTERNAL_KEY_CONVERTER
              value: org.apache.kafka.connect.json.JsonConverter
            - name: CONNECT_INTERNAL_VALUE_CONVERTER
              value: org.apache.kafka.connect.json.JsonConverter
            - name: CONNECT_KEY_CONVERTER
              value: org.apache.kafka.connect.json.JsonConverter
            - name: CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR
              value: "1"
            - name: CONNECT_OFFSET_STORAGE_TOPIC
              value: _connect-offsets
            - name: CONNECT_PLUGIN_PATH
              value: /usr/share/java,/usr/share/connectors,/usr/share/connectors/clickhouse-kafka-connect-v0.0.13-beta-all.jar
            - name: CONNECT_REST_ADVERTISED_HOST_NAME
              value: connector
            - name: CONNECT_REST_PORT
              value: "8083"
            - name: CONNECT_STATUS_STORAGE_REPLICATION_FACTOR
              value: "1"
            - name: CONNECT_STATUS_STORAGE_TOPIC
              value: _connect-status
            - name: CONNECT_VALUE_CONVERTER
              value: org.apache.kafka.connect.json.JsonConverter
            - name: KEEPER_MAP_PATH_PREFIX
              value: /keeper_map_tables
          image: hub.tess.io/bowsong/connector:latest
          name: connector
          ports:
            - containerPort: 8123
          resources: {}
      restartPolicy: Always
status: {}
