apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o deploy/dev_distributed/resources
    kompose.version: 1.28.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: zookeeper-clickhouse
  name: zookeeper-clickhouse
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: zookeeper-clickhouse
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o deploy/dev_distributed/resources
        kompose.version: 1.28.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/clickhouse-kafka-connect-default: "true"
        io.kompose.service: zookeeper-clickhouse
    spec:
      containers:
        - env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
            - name: ZOOKEEPER_TICK_TIME
              value: "2000"
          image: confluentinc/cp-zookeeper:7.3.2
          name: zookeeper-clickhouse
          resources: {}
      restartPolicy: Always
status: {}
